name: FreeBSD CI

on:
  push:
  pull_request:

jobs:
  freebsd:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["12.4", "14.2"]
    steps:
      - uses: actions/checkout@v4

      - name: Run on FreeBSD
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: ${{ matrix.version }}
          architecture: x86-64
          shell: sh
          run: |
            set -eux
            make
            ./testprog
            objdump -d testprog | grep -A6 "puts@plt"
